[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "cd .. && npx pnpm@7.5.0 i --store=./node_modules/.pnpm-store && pnpm run deploy && cd playground"
  ignore = "git diff --quiet HEAD^ HEAD . ../packages"

[functions]
  node_bundler = "esbuild"
